//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edilex_Documents_DocumentPartRecord
    {
        public int Id { get; set; }
        public Nullable<int> ContentItemRecord_id { get; set; }
        public Nullable<int> RFP_id { get; set; }
        public string DocBlockTree { get; set; }
        public string DocumentType { get; set; }
        public string DocumentStyle { get; set; }
        public string DocumentState { get; set; }
    }
}
